install/gtkradiant usr/bin/
debian/gtkradiant.desktop usr/share/applications/
# Place helpers in libdir so they don't conflict with other packages.
tools/bspc/bspc usr/lib/x86_64-linux-gnu/gtkradiant/
install/q3data usr/lib/x86_64-linux-gnu/gtkradiant/
install/q3map2 usr/lib/x86_64-linux-gnu/gtkradiant/
install/q3map2_urt usr/lib/x86_64-linux-gnu/gtkradiant/
install/base usr/share/gtkradiant/
install/bitmaps usr/share/gtkradiant/
install/locale usr/share/
install/modules/bitmaps usr/share/gtkradiant/modules/
install/modules/*.so usr/lib/x86_64-linux-gnu/gtkradiant/modules/
# These are actually data files, but patching bobtoolz to look
# elsewhere is tricky:
install/modules/bt usr/lib/x86_64-linux-gnu/gtkradiant/modules/
